# Enabling H2 Console
spring:
  h2:
    console:
      enabled: true
      path: /h2 # http://localhost:8080/products/h2
  datasource:
    url: jdbc:h2:mem:testdb
    #url: jdbc:h2:file:/data/demo
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect